// frontend/lib/curated-games.ts
// Auto-generated curated game list
// Generated on 2025-11-12T05:27:04.426Z

export const CURATED_GAME_SLUGS = [
  'aviator', // Aviator (Spribe)
  'beach-life', // Beach Life (Playtech)
  'big-bass-bonanza', // Big Bass Bonanza (Pragmatic Play)
  'blood-suckers', // Blood Suckers (NetEnt)
  'blood-suckers-megaways', // Blood Suckers Megaways (Red Tiger Gaming)
  'book-of-99', // Book of 99 (Relax Gaming)
  'book-of-dead', // Book of Dead (Play'n GO)
  'buffalo-blitz', // Buffalo Blitz (Playtech)
  'butterfly-staxx', // Butterfly Staxx (NetEnt)
  'cleopatra-gold', // Cleopatra Gold (IGT)
  'dead-or-alive', // Dead or Alive (NetEnt)
  'divine-fortune-megaways', // Divine Fortune Megaways (NetEnt)
  'finns-golden-tavern', // Finn's Golden Tavern (NetEnt)
  'fruit-shop', // Fruit Shop (NetEnt)
  'gates-of-olympus', // Gates of Olympus (Pragmatic Play)
  'gates-of-olympus-1000', // Gates of Olympus 1000 (Pragmatic Play)
  'gonzos-quest', // Gonzo's Quest (NetEnt)
  'guns-n-roses', // Guns N' Roses (NetEnt)
  'jackpot-giant', // Jackpot Giant (Playtech)
  'jimi-hendrix', // Jimi Hendrix (NetEnt)
  'mega-joker', // Mega Joker (NetEnt)
  'money-train', // Money Train (Relax Gaming)
  'money-train-2', // Money Train 2 (Relax Gaming)
  'money-train-3', // Money Train 3 (Relax Gaming)
  'piggy-riches', // Piggy Riches (NetEnt)
  'pirots-2', // Pirots 2 (Elk Studios)
  'pirots-3', // Pirots 3 (Elk Studios)
  'razor-shark', // Razor Shark (Push Gaming)
  'reactoonz', // Reactoonz (Play'n GO)
  'starburst', // Starburst (NetEnt)
  'starburst-xxxtreme', // Starburst XXXtreme (NetEnt)
  'sugar-rush-1000', // Sugar Rush 1000 (Pragmatic Play)
  'sweet-bonanza', // Sweet Bonanza (Pragmatic Play)
  'sweet-bonanza-1000', // Sweet Bonanza 1000 (Pragmatic Play)
  'thunderstruck', // Thunderstruck (Games Global)
  'thunderstruck-2', // ThunderStruck II (Games Global)
  'tombstone-rip', // Tombstone R.I.P (Nolimit City)
  'valley-of-the-gods', // Valley of the Gods (Yggdrasil Gaming)
  'wheel-of-fortune-triple-extreme-spin', // Wheel of Fortune Triple Extreme Spin (IGT)
  'white-rabbit-megaways', // White Rabbit Megaways (Big Time Gaming)
] as const

export const CURATED_GAME_IDS = [
  15373, // Aviator (Spribe)
  28644, // Beach Life (Playtech)
  5356, // Big Bass Bonanza (Pragmatic Play)
  33371, // Blood Suckers (NetEnt)
  4771, // Blood Suckers Megaways (Red Tiger Gaming)
  17640, // Book of 99 (Relax Gaming)
  9914, // Book of Dead (Play'n GO)
  12586, // Buffalo Blitz (Playtech)
  9661, // Butterfly Staxx (NetEnt)
  12849, // Cleopatra Gold (IGT)
  9671, // Dead or Alive (NetEnt)
  3244, // Divine Fortune Megaways (NetEnt)
  9687, // Finn's Golden Tavern (NetEnt)
  9692, // Fruit Shop (NetEnt)
  5397, // Gates of Olympus (Pragmatic Play)
  16716, // Gates of Olympus 1000 (Pragmatic Play)
  9699, // Gonzo's Quest (NetEnt)
  9704, // Guns N' Roses (NetEnt)
  28706, // Jackpot Giant (Playtech)
  9716, // Jimi Hendrix (NetEnt)
  9729, // Mega Joker (NetEnt)
  17668, // Money Train (Relax Gaming)
  17669, // Money Train 2 (Relax Gaming)
  1806, // Money Train 3 (Relax Gaming)
  9738, // Piggy Riches (NetEnt)
  17916, // Pirots 2 (Elk Studios)
  27657, // Pirots 3 (Elk Studios)
  18780, // Razor Shark (Push Gaming)
  29087, // Reactoonz (Play'n GO)
  9759, // Starburst (NetEnt)
  9760, // Starburst XXXtreme (NetEnt)
  20070, // Sugar Rush 1000 (Pragmatic Play)
  5483, // Sweet Bonanza (Pragmatic Play)
  23537, // Sweet Bonanza 1000 (Pragmatic Play)
  11539, // Thunderstruck (Games Global)
  11540, // ThunderStruck II (Games Global)
  2868, // Tombstone R.I.P (Nolimit City)
  8803, // Valley of the Gods (Yggdrasil Gaming)
  12938, // Wheel of Fortune Triple Extreme Spin (IGT)
  3387, // White Rabbit Megaways (Big Time Gaming)
  22323, // Sic Bo (game 1)
  14228, // Sic Bo (game 2)
  22324, // Sic Bo (game 3)
  22512, // Mahjong (game 1)
  22510, // Mahjong (game 2)
  20191, // Mahjong (game 3)
  18925, // Mahjong (game 4)
  18183, // Mahjong (game 5)
  16645, // Mahjong (game 6)
  14301, // Mahjong (game 7)
  10281, // Mahjong (game 8)
  12670, // Keno (game 1)
  15378, // Keno (game 2)
  19630, // Keno (game 3)
  17163, // Keno (game 4)
  22452, // Keno (game 5)
  17087, // Keno (game 6)
  23571, // Classic (game 1)
  11198, // Classic (game 2)
  11131, // Classic (game 3)
  11171, // Classic (game 4)
  11128, // Classic (game 5)
  11254, // Classic (game 6)
] as const

export type CuratedGameSlug = typeof CURATED_GAME_SLUGS[number]
